# Generated by Django 5.2.4 on 2025-08-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(default='region', max_length=255)),
                ('name_en', models.CharField(default='region', max_length=255)),
                ('name_uz', models.CharField(default='region', max_length=255)),
                ('name_ru', models.CharField(default='region', max_length=255)),
                ('post_code', models.CharField(default=0, max_length=10)),
                ('soato', models.CharField(default=1, max_length=20, unique=True, verbose_name='soato')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(default='Name', max_length=255, verbose_name='Name')),
                ('name_uz', models.CharField(default='Name', max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(default='Name', max_length=255, verbose_name='Name')),
                ('name_ru', models.CharField(default='Name', max_length=255, verbose_name='Name')),
                ('soato', models.CharField(default=1, max_length=20, unique=True, verbose_name='soato')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='common.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'district',
            },
        ),
    ]
